name: Validate Builds

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build_on_ubuntu:
    runs-on: ubuntu-18.04

    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libblkid-dev libbsd-dev gettext autopoint autoconf bison libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-1 liblz4-dev curl python3-setuptools
          sudo apt-get install libmongoc-1.0-0 libbson-1.0-0 libssl-dev libsasl2-dev
          python3 -m pip install --user setuptools_rust wheel
          python3 -m pip install --user poetry

      - uses: actions/checkout@v2
        with:
          repository: 'bvasandani/workflows'
          ref: 'hsemaster'
          path: 'hse'

      - name : Build and install hse
        working-directory: ./hse
        run: |
          poetry install
          sed -i.bak "s,ssh://git@bitbucket.micron.com/hse/hse-python.git,https://${{ secrets.GH_TOKEN }}@github.com/bhaveshvasandani/hse-python.git,g" subprojects/hse-python.wrap
          poetry run meson builddir -Dbuildtype=${{ matrix.build_type }} -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true
          poetry run meson install -C builddir --destdir=/tmp/hse

       - uses: actions/checkout@v2
 
       - name: Build mongo
         run: |
           scons -j$(nproc) --dbg=off --opt=on CPPPATH=/tmp/hse/opt/hse/include/hse-2 LIBPATH=/tmp/hse/opt/hse/lib64 --disable-warnings-as-errors all hse_unit_tests
           cd build/opt/mongo/db/storage/hse
           mkdir ./kvdb_home_test
           ./hse_test_harness.py ${{ github.run_id }} /opt/hse/bin/hse2 ./kvdb_home_test
         
